on:
  push:
    branches:
      - main
      - master
      - staging
      - trying
  pull_request:

name: Run tests
jobs:
  wkt:
    name: wkt
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    container:
      image: georust/geo-ci
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: cargo install cargo-all-features
      - run: cargo build-all-features
      - run: cargo test-all-features
